// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBuilding.Infrastructure;

namespace SmartBuilding.Infrastructure.Migrations
{
    [DbContext(typeof(SmartBuildingDataContext))]
    [Migration("20210608180435_PeriodLimits")]
    partial class PeriodLimits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartBuilding.Models.Hvac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenancePeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("NextMaintenanceDays")
                        .HasColumnType("int");

                    b.Property<int>("ProjectedLifePeriodYears")
                        .HasColumnType("int");

                    b.Property<int>("ProjectedLifeYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hvac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2616ff7-d0d2-44d1-a706-acb0d2ba473d"),
                            DateTime = new DateTime(2021, 6, 8, 18, 4, 35, 431, DateTimeKind.Utc).AddTicks(5503),
                            MaintenancePeriodDays = 120,
                            NextMaintenanceDays = 60,
                            ProjectedLifePeriodYears = 48,
                            ProjectedLifeYears = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
