// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBuilding.Infrastructure;

namespace SmartBuilding.Infrastructure.Migrations
{
    [DbContext(typeof(SmartBuildingDataContext))]
    partial class SmartBuildingDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartBuilding.Models.Hvac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NextMaintenanceDays")
                        .HasColumnType("int");

                    b.Property<int>("ProjectedLifeYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hvac");
                });
#pragma warning restore 612, 618
        }
    }
}
