trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

variables:
- group: DemoSmartBuilding-DEV

name: DemoSmartBuilding.$(Date:yyyyMMdd)-$(Rev:rr)

stages:
- stage: Build
  displayName: 👷 CI
  jobs:
  - job: CreateReactAppBuild
    displayName: "⚛️ Create React App Build"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
    - task: YarnInstaller@3
      inputs:
        versionSpec: '1.x'
    - script:
        yarn install
      displayName: '🤘 yarn install'
    - script:
        yarn build
      displayName: '🤞 yarn build'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
    - task: ArchiveFiles@2
      displayName: '📦 Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish'
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "WebApp"
        publishLocation: "Container"

- template: templates/deploy-image.yml
  parameters:
    name: '🚀 Deploy Dev'
    environment: smartbuildingdev
    variablesGroup: DemoSmartBuilding-DEV